const STYLE_ID = 'dsh-godot-ai/workspace'

const CSS = `
:root[data-dga-mode=godot-creator],:root[data-dga-mode=godot-creator-adaptive]{--dga-accent:#478cbf;--dga-accent-soft:color-mix(in srgb,#478cbf 11%,transparent);--dga-accent-line:color-mix(in srgb,#478cbf 34%,var(--dsw-alias-border-l2))}
.dga-ws-header{display:inline-flex;align-items:center;min-width:0;gap:6px;height:26px;padding:2px 8px 2px 5px;border:1px solid var(--dga-accent-line);border-radius:8px;background:var(--dga-accent-soft);color:var(--dsw-alias-label-primary);font:inherit;cursor:pointer;transition:border-color 160ms ease,background 160ms ease}.dga-ws-header:hover{background:color-mix(in srgb,#478cbf 17%,transparent);border-color:color-mix(in srgb,#478cbf 54%,var(--dsw-alias-border-l2))}.dga-ws-header:focus-visible,.dga-ws-icon-button:focus-visible,.dga-ws-section button:focus-visible{outline:2px solid var(--dga-accent);outline-offset:2px}.dga-ws-header img{flex:none}.dga-ws-header-name{font-size:12px;font-weight:650}.dga-ws-header-project{max-width:160px;overflow:hidden;color:var(--dsw-alias-label-secondary);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.dga-ws-status-dot{display:inline-block;flex:none;width:7px;height:7px;border-radius:50%;background:var(--dsw-alias-label-dimmed);box-shadow:0 0 0 3px color-mix(in srgb,var(--dsw-alias-label-dimmed) 12%,transparent)}[data-tone=ready] .dga-ws-status-dot{background:#3d9a6d}[data-tone=playing] .dga-ws-status-dot{background:var(--dga-accent);animation:dga-ws-pulse 1.7s ease-in-out infinite}[data-tone=warn] .dga-ws-status-dot{background:var(--dsw-alias-state-warn-primary)}[data-tone=offline] .dga-ws-status-dot{background:var(--dsw-alias-label-dimmed)}
.dga-ws-overlay{position:fixed;z-index:1100;inset:0;overflow:hidden;background:color-mix(in srgb,#07111a 34%,transparent);backdrop-filter:blur(2px);animation:dga-ws-fade 160ms ease-out}.dga-ws-drawer{position:absolute;inset:0 0 0 auto;display:flex;width:min(380px,100vw);max-width:100%;flex-direction:column;border-left:1px solid var(--dsw-alias-border-l2);background:var(--dsw-alias-bg-base);box-shadow:-18px 0 48px color-mix(in srgb,#07111a 24%,transparent);color:var(--dsw-alias-label-primary);animation:dga-ws-slide 180ms ease-out}.dga-ws-drawer-head{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:18px 18px 14px;border-bottom:1px solid var(--dsw-alias-border-l1)}.dga-ws-brand{display:flex;min-width:0;align-items:center;gap:10px}.dga-ws-brand img{flex:none}.dga-ws-brand span,.dga-ws-section-title>span{display:block;color:var(--dga-accent);font-size:10px;font-weight:750;letter-spacing:.11em;text-transform:uppercase}.dga-ws-brand h2{margin:2px 0 0;font-size:18px;line-height:22px;font-weight:650}.dga-ws-icon-button{display:grid;width:30px;height:30px;place-items:center;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);cursor:pointer}.dga-ws-icon-button:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dga-ws-icon-button svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:1.5;stroke-linecap:round}.dga-ws-scroll{display:flex;min-width:0;min-height:0;flex:1;flex-direction:column;gap:12px;padding:14px 14px max(24px,env(safe-area-inset-bottom));overflow-x:hidden;overflow-y:auto}
.dga-ws-overview{padding:15px;border:1px solid var(--dga-accent-line);border-radius:14px;background:linear-gradient(145deg,var(--dga-accent-soft),transparent 70%)}.dga-ws-overview-top{display:flex;align-items:center;gap:8px;color:var(--dsw-alias-label-secondary);font-size:11px}.dga-ws-overview-top strong{color:var(--dsw-alias-label-primary);font-size:12px}.dga-ws-overview-top>span:last-child{margin-left:auto}.dga-ws-project{margin-top:14px;font-size:20px;line-height:26px;font-weight:650;text-wrap:pretty}.dga-ws-scene{display:flex;min-width:0;align-items:center;justify-content:space-between;gap:12px;margin-top:4px;color:var(--dsw-alias-label-secondary);font-size:11px}.dga-ws-scene code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dga-ws-scene span{flex:none;text-transform:capitalize}.dga-ws-error{margin:0;padding:10px 12px;border-radius:10px;background:var(--dsw-alias-interactive-bg-hover-danger);color:var(--dsw-alias-state-error-primary);font-size:12px;line-height:18px}
.dga-ws-section{padding:14px;border:1px solid var(--dsw-alias-border-l2);border-radius:14px;background:var(--dsw-alias-bg-layer-1)}.dga-ws-section-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.dga-ws-section-title button{padding:4px 7px;border:0;border-radius:6px;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:11px;cursor:pointer}.dga-ws-section-title button:hover{background:var(--dsw-alias-interactive-bg-hover);color:var(--dsw-alias-label-primary)}.dga-ws-section-title button:disabled{cursor:default;opacity:.55}.dga-ws-facts{display:flex;margin:0;flex-direction:column;gap:9px}.dga-ws-facts>div{display:grid;grid-template-columns:96px minmax(0,1fr);gap:10px}.dga-ws-facts dt{color:var(--dsw-alias-label-tertiary);font-size:11px}.dga-ws-facts dd{min-width:0;margin:0;overflow-wrap:anywhere;color:var(--dsw-alias-label-primary);font-size:11px;line-height:16px}.dga-ws-workflows{display:flex;flex-direction:column;gap:7px}.dga-ws-workflows button{display:grid;grid-template-columns:30px minmax(0,1fr) 16px;align-items:center;gap:10px;width:100%;padding:10px;border:1px solid transparent;border-radius:10px;background:color-mix(in srgb,var(--dsw-alias-label-primary) 4%,transparent);color:var(--dsw-alias-label-primary);text-align:left;cursor:pointer}.dga-ws-workflows button:hover{border-color:var(--dga-accent-line);background:var(--dga-accent-soft)}.dga-ws-workflows button:disabled{cursor:not-allowed;opacity:.45}.dga-ws-workflows button>span:nth-child(2){display:flex;min-width:0;flex-direction:column;gap:2px}.dga-ws-workflows strong{font-size:12px;font-weight:620}.dga-ws-workflows small{color:var(--dsw-alias-label-secondary);font-size:10px;line-height:14px;text-wrap:pretty}.dga-ws-workflows svg{width:14px;height:14px;fill:none;stroke:currentColor;stroke-width:1.4;stroke-linecap:round;stroke-linejoin:round}.dga-ws-workflow-tag{display:grid;width:28px;height:28px;place-items:center;border-radius:8px;background:var(--dga-accent-soft);color:var(--dga-accent);font-size:10px;font-weight:750}.dga-ws-workflow-help{margin:9px 0 0;color:var(--dsw-alias-label-tertiary);font-size:10px;line-height:15px;text-wrap:pretty}.dga-ws-addon-note{display:flex;flex-direction:column;gap:3px;padding:2px 4px;color:var(--dsw-alias-label-tertiary);font-size:10px;line-height:15px}.dga-ws-addon-note strong{color:var(--dsw-alias-label-secondary);font-size:11px}.dga-ws-addon-note[data-connected=true] strong{color:#3d9a6d}
.dga-ws-route-options{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.dga-ws-route-options button{min-height:32px;border:1px solid var(--dsw-alias-border-l2);border-radius:8px;background:transparent;color:var(--dsw-alias-label-secondary);font:inherit;font-size:11px;cursor:pointer}.dga-ws-route-options button[data-selected=true]{border-color:var(--dga-accent);background:var(--dga-accent-soft);color:var(--dsw-alias-label-primary);font-weight:650}.dga-ws-route-options button:disabled{cursor:default;opacity:.62}.dga-ws-adaptive .dga-ws-facts{margin-top:10px}
@keyframes dga-ws-fade{from{opacity:0}}@keyframes dga-ws-slide{from{transform:translateX(24px);opacity:.65}}@keyframes dga-ws-pulse{50%{box-shadow:0 0 0 5px color-mix(in srgb,#478cbf 6%,transparent)}}
@media(max-width:640px){.dga-ws-header{height:44px;padding-inline:10px}.dga-ws-header-project{display:none}.dga-ws-overlay{display:flex;align-items:flex-end}.dga-ws-drawer{position:relative;inset:auto;width:100%;max-height:min(82dvh,760px);border-top:1px solid var(--dsw-alias-border-l2);border-left:0;border-radius:18px 18px 0 0;box-shadow:0 -18px 48px color-mix(in srgb,#07111a 24%,transparent);animation-name:dga-ws-sheet}.dga-ws-drawer-head{padding-top:16px}.dga-ws-drawer-head:before{position:absolute;top:7px;left:50%;width:34px;height:3px;border-radius:2px;background:var(--dsw-alias-border-l4);content:"";transform:translateX(-50%)}.dga-ws-icon-button{width:44px;height:44px}.dga-ws-section-title button{min-width:44px;min-height:44px;margin:-10px -7px -10px 0}.dga-ws-workflows button{min-height:60px}.dga-ws-facts>div{grid-template-columns:88px minmax(0,1fr)}}@keyframes dga-ws-sheet{from{transform:translateY(24px);opacity:.65}}
@media(prefers-reduced-motion:reduce){.dga-ws-header,.dga-ws-overlay,.dga-ws-drawer{transition:none;animation:none}[data-tone=playing] .dga-ws-status-dot{animation:none}}
`

export function installWorkspaceStyles(): () => void {
  const existing = document.querySelector(`style[data-plugin-css="${STYLE_ID}"]`)
  if (existing !== null) return () => undefined
  const style = document.createElement('style')
  style.dataset.plugin = 'dsh-godot-ai'
  style.dataset.pluginCss = STYLE_ID
  style.textContent = CSS
  document.head.append(style)
  return () => { style.remove() }
}
